export interface BoxPin {
  id: string;
  code: string;
  category: 'MAIN_BOX' | 'SUB_BOX';
  status: 'ACTIVE' | 'NEEDS_TAG' | 'ISSUE';
  siteName: string;
  address: string;
  parentCode?: string;
  equipmentItems: string[];
  clientsCount: number;
  latitude: number;
  longitude: number;
  // Rich telecom attributes
  zone: string;
  tier: string;
  portsUsed: number;
  totalPorts: number;
  opticalLoss: string;
  circuitBreaker: string;
  voltage: string;
  temperature: string;
  installedDate: string;
  lastScannedBy?: string;
  lastScannedAt?: string;
}

export const BOX_PINS: BoxPin[] = [
  {
    id: '1',
    code: 'DB-MN-01',
    category: 'MAIN_BOX',
    status: 'ACTIVE',
    siteName: 'Iligan City Hall / Aguinaldo Central Hub',
    address: 'Aguinaldo St, Poblacion, Iligan City',
    zone: 'Poblacion',
    tier: 'Tier 1 · Main Feeder',
    equipmentItems: [
      'Main Optical Feeder 48-Port',
      'Primary Circuit Breaker 63A',
      'Surge Protector',
    ],
    clientsCount: 142,
    portsUsed: 44,
    totalPorts: 48,
    opticalLoss: '-18.2 dBm',
    circuitBreaker: '63A 2P MCB',
    voltage: '228.4 V',
    temperature: '31.2 °C',
    installedDate: '2024-03-15',
    lastScannedBy: 'Engr. R. Datu',
    lastScannedAt: 'Today, 09:42 AM',
    latitude: 8.2280,
    longitude: 124.2452,
  },
  {
    id: '2',
    code: 'DB-MN-02',
    category: 'MAIN_BOX',
    status: 'ACTIVE',
    siteName: 'Aguinaldo Secondary Distribution Center',
    address: 'Roxas Ave cor. Aguinaldo, Iligan City',
    zone: 'Poblacion',
    tier: 'Tier 1 · Main Feeder',
    equipmentItems: ['Main Optical Feeder 24-Port', 'Primary Breaker 40A'],
    clientsCount: 98,
    portsUsed: 21,
    totalPorts: 24,
    opticalLoss: '-18.5 dBm',
    circuitBreaker: '40A 2P MCB',
    voltage: '230.1 V',
    temperature: '33.0 °C',
    installedDate: '2024-04-10',
    lastScannedBy: 'Tech. M. Santos',
    lastScannedAt: 'Yesterday, 04:15 PM',
    latitude: 8.2240,
    longitude: 124.2420,
  },
  {
    id: '3',
    code: 'DB-SB-02',
    category: 'SUB_BOX',
    status: 'ACTIVE',
    parentCode: 'DB-MN-01',
    siteName: 'MSU-IIT Tibanga Campus Node',
    address: 'Andres Bonifacio Ave, Tibanga, Iligan City',
    zone: 'Tibanga',
    tier: 'Tier 2 · Sub-Distribution',
    equipmentItems: ['1:8 Optical Splitter', 'Terminal Block 16-Port', '15A Breaker'],
    clientsCount: 24,
    portsUsed: 14,
    totalPorts: 16,
    opticalLoss: '-19.8 dBm',
    circuitBreaker: '15A 1P MCB',
    voltage: '229.0 V',
    temperature: '29.5 °C',
    installedDate: '2024-05-02',
    lastScannedBy: 'Tech. K. Alonto',
    lastScannedAt: 'Today, 11:20 AM',
    latitude: 8.2410,
    longitude: 124.2435,
  },
  {
    id: '4',
    code: 'DB-SB-03',
    category: 'SUB_BOX',
    status: 'ACTIVE',
    parentCode: 'DB-MN-01',
    siteName: 'Tubod Commercial Distribution Node',
    address: 'Macapagal Highway, Tubod, Iligan City',
    zone: 'Tubod',
    tier: 'Tier 2 · Sub-Distribution',
    equipmentItems: ['1:8 Optical Splitter', 'Terminal Block', '15A Breaker'],
    clientsCount: 18,
    portsUsed: 15,
    totalPorts: 16,
    opticalLoss: '-20.1 dBm',
    circuitBreaker: '15A 1P MCB',
    voltage: '227.8 V',
    temperature: '34.1 °C',
    installedDate: '2024-05-18',
    lastScannedBy: 'Tech. J. Morales',
    lastScannedAt: 'Oct 01, 08:30 AM',
    latitude: 8.2120,
    longitude: 124.2380,
  },
  {
    id: '5',
    code: 'DB-SB-04',
    category: 'SUB_BOX',
    status: 'NEEDS_TAG',
    parentCode: 'DB-MN-02',
    siteName: 'Robinsons Place Iligan - Floor 2 Rack',
    address: 'Macapagal Ave, Iligan City',
    zone: 'Tubod',
    tier: 'Tier 2 · Sub-Distribution',
    equipmentItems: ['1:16 Optical Splitter', '2x 20A Breakers'],
    clientsCount: 32,
    portsUsed: 12,
    totalPorts: 16,
    opticalLoss: '-21.4 dBm',
    circuitBreaker: '20A 1P MCB',
    voltage: '231.0 V',
    temperature: '28.0 °C',
    installedDate: '2024-06-01',
    lastScannedBy: 'Unverified',
    lastScannedAt: 'Pending Physical Tagging',
    latitude: 8.2200,
    longitude: 124.2340,
  },
  {
    id: '6',
    code: 'DB-SB-05',
    category: 'SUB_BOX',
    status: 'NEEDS_TAG',
    parentCode: 'DB-MN-01',
    siteName: 'Tambo Terminal Distribution Enclosure',
    address: 'Hinaplanon-Tambo Highway, Iligan City',
    zone: 'Tambo',
    tier: 'Tier 2 · Sub-Distribution',
    equipmentItems: ['1:8 Optical Splitter', 'Terminal Block'],
    clientsCount: 14,
    portsUsed: 8,
    totalPorts: 16,
    opticalLoss: '-22.0 dBm',
    circuitBreaker: '15A 1P MCB',
    voltage: '226.5 V',
    temperature: '32.4 °C',
    installedDate: '2024-06-20',
    lastScannedBy: 'Unverified',
    lastScannedAt: 'Pending Physical Tagging',
    latitude: 8.2510,
    longitude: 124.2620,
  },
  {
    id: '7',
    code: 'DB-SB-06',
    category: 'SUB_BOX',
    status: 'ISSUE',
    parentCode: 'DB-MN-02',
    siteName: 'Del Carmen Secondary Sub-Box',
    address: 'Del Carmen, Iligan City',
    zone: 'Del Carmen',
    tier: 'Tier 2 · Sub-Distribution',
    equipmentItems: [
      '1:8 Splitter (Port 3 Degraded)',
      '20A Breaker (High Temp Alert)',
    ],
    clientsCount: 16,
    portsUsed: 16,
    totalPorts: 16,
    opticalLoss: '-26.8 dBm (Degraded)',
    circuitBreaker: '20A 1P MCB',
    voltage: '219.2 V (Low)',
    temperature: '42.5 °C (High Temp Alert)',
    installedDate: '2024-07-05',
    lastScannedBy: 'Tech. D. Ramos',
    lastScannedAt: 'Today, 07:15 AM',
    latitude: 8.2320,
    longitude: 124.2650,
  },
];
